// PDF exports of maintenance records, laid out around what a DOT
// inspector asks for under 49 CFR 396.3 (vehicle identification, the nature
// and due date of scheduled maintenance, and a dated record of what was done).
// jsPDF is loaded from cdnjs the first time a PDF is made.

const JSPDF_URL = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
const AUTOTABLE_URL = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.2/jspdf.plugin.autotable.min.js';

let libPromise;
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error(`Could not load ${src}`));
    document.head.append(s);
  });
}
function loadPdfLib() {
  libPromise ??= loadScript(JSPDF_URL).then(() => loadScript(AUTOTABLE_URL)).then(() => window.jspdf.jsPDF);
  return libPromise;
}

const fmt = new Intl.NumberFormat('en-US');
const num = (n) => (n == null || n === '' ? '—' : fmt.format(n));
function niceDate(value) {
  if (!value) return '—';
  const d = /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T12:00:00`) : new Date(value);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}
const entryDate = (e) => (e.date ? niceDate(e.date) : 'Not written');
const workText = (e) => `${e.type === 'repair' ? 'Repair: ' : ''}${e.itemName || e.itemId}`;
const fileSafe = (s) => String(s).replace(/[^A-Za-z0-9-]+/g, '-').replace(/^-|-$/g, '');

const RETENTION_NOTE = 'Retention: maintenance records (49 CFR 396.3) are kept where the vehicle is housed or maintained for 1 year and for '
  + '6 months after the vehicle leaves the carrier\'s control. Annual inspection reports: 14 months (396.21). Driver vehicle inspection '
  + 'reports: 3 months (396.11).';

const CATEGORY = { engine: 'Engine', chassis: 'Chassis', regulatory: 'DOT' };

function header(doc, title, company, subtitle) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.text(title, 40, 50);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const carrier = [company?.name || 'Motor carrier: ______________________', company?.usdot ? `USDOT ${company.usdot}` : null]
    .filter(Boolean).join('   ·   ');
  doc.text(carrier, 40, 68);
  doc.setTextColor(100);
  doc.text(subtitle, 40, 83);
  doc.setTextColor(0);
  return 98;
}

function footers(doc) {
  const pages = doc.getNumberOfPages();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pages; i += 1) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(110);
    doc.text(doc.splitTextToSize(RETENTION_NOTE, w - 80), 40, h - 34);
    doc.text(`Generated by aslog.dev on ${niceDate(new Date().toISOString())}`, 40, h - 14);
    doc.text(`Page ${i} of ${pages}`, w - 40, h - 14, { align: 'right' });
    doc.setTextColor(0);
  }
}

function sectionTitle(doc, text, y) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11.5);
  doc.text(text, 40, y);
  doc.setFont('helvetica', 'normal');
  return y + 8;
}

const tableStyle = {
  styles: { fontSize: 8.5, cellPadding: 4, valign: 'top', overflow: 'linebreak' },
  headStyles: { fillColor: [31, 95, 214], textColor: 255, fontStyle: 'bold' },
  alternateRowStyles: { fillColor: [244, 246, 249] },
  margin: { left: 40, right: 40, bottom: 60 },
};

function lastDoneText(last) {
  if (!last) return 'Not on record';
  if (last.source === 'baseline') return `Not on record (tracking began ${niceDate(last.date)})`;
  return `${last.date ? niceDate(last.date) : 'Date not written'} at ${num(last.miles)} mi`;
}

function nextDueText(r) {
  const parts = [];
  if (r.dueMiles != null) parts.push(`${num(r.dueMiles)} mi`);
  if (r.dueHours != null) parts.push(`${num(r.dueHours)} engine h`);
  if (r.dueDate) parts.push(niceDate(r.dueDate));
  return parts.length ? parts.join(' or ') : '—';
}

const STATUS = { overdue: 'OVERDUE', soon: 'Due soon', ok: 'OK', done: 'Done', 'n/a': 'N/A', 'as-needed': 'As needed', 'no-record': '—' };

/** Adds one truck's maintenance record to `doc` starting on the current page. */
function addTruckRecord(doc, { vehicle: v, rows, intervalText, entries, dutyText, company, from, to, startY }) {
  let y = startY ?? header(doc, 'Vehicle Maintenance Record', company,
    `Unit ${v.name}  ·  Records ${from || to ? `${from ? niceDate(from) : 'start'} to ${to ? niceDate(to) : 'today'}` : 'all dates'}`);

  // 1. Vehicle identification — 396.3(b)(1)
  y = sectionTitle(doc, 'Vehicle identification  (49 CFR 396.3(b)(1))', y + 4);
  doc.autoTable({
    ...tableStyle,
    startY: y,
    theme: 'grid',
    body: [
      ['Company unit number', v.name || '—', 'VIN (serial number)', v.vin || '—'],
      ['Year / make', `${v.year || '—'} ${v.make || ''}`.trim(), 'Model', v.model || '—'],
      ['License plate', v.plate || '—', 'Odometer', `${num(v.odometerMiles)} mi${v.odometerTime ? ` (${niceDate(v.odometerTime)})` : ''}`],
      ['Engine hours', num(v.engineHours), 'Schedule basis', dutyText || 'Manufacturer schedule'],
    ],
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 110 }, 2: { fontStyle: 'bold', cellWidth: 110 } },
  });
  y = doc.lastAutoTable.finalY + 18;

  // 2. Nature and due date of inspection & maintenance — 396.3(b)(2)
  y = sectionTitle(doc, 'Scheduled inspection and maintenance: nature and due date  (49 CFR 396.3(b)(2))', y);
  doc.autoTable({
    ...tableStyle,
    startY: y,
    head: [['Service', 'Type', 'Interval', 'Last done', 'Next due', 'Status']],
    body: rows.length
      ? rows.map((r) => [
        r.item.name, CATEGORY[r.schedule.category] ?? '', intervalText(r.item), lastDoneText(r.last), nextDueText(r), STATUS[r.status] ?? r.status,
      ])
      : [[{ content: 'No maintenance schedule assigned to this vehicle yet.', colSpan: 6, styles: { textColor: 110 } }]],
    columnStyles: { 0: { cellWidth: 130 }, 1: { cellWidth: 44 }, 2: { cellWidth: 92 }, 5: { cellWidth: 52 } },
    didParseCell: (d) => {
      if (d.section === 'body' && d.column.index === 5 && d.cell.raw === 'OVERDUE') {
        d.cell.styles.textColor = [198, 40, 40];
        d.cell.styles.fontStyle = 'bold';
      }
    },
  });
  y = doc.lastAutoTable.finalY + 18;

  // 3. Record of inspection, repairs and maintenance — 396.3(b)(3)
  if (y > doc.internal.pageSize.getHeight() - 140) { doc.addPage(); y = 50; }
  y = sectionTitle(doc, 'Record of inspection, repairs and maintenance  (49 CFR 396.3(b)(3))', y);
  doc.autoTable({
    ...tableStyle,
    startY: y,
    head: [['Date', 'Work performed', 'Odometer', 'Engine h', 'Shop / notes']],
    body: entries.length
      ? entries.map((e) => [entryDate(e), workText(e), num(e.miles), num(e.hours), e.note || ''])
      : [[{ content: 'No services logged in aslog.dev for this period.', colSpan: 5, styles: { textColor: 110 } }]],
    columnStyles: { 0: { cellWidth: 70 }, 2: { cellWidth: 62, halign: 'right' }, 3: { cellWidth: 52, halign: 'right' } },
  });
  y = doc.lastAutoTable.finalY + 18;

  // 4. Annual (periodic) inspection — 396.17
  const annual = rows.find((r) => r.schedule.id === 'dot-annual');
  if (annual) {
    if (y > doc.internal.pageSize.getHeight() - 110) { doc.addPage(); y = 50; }
    y = sectionTitle(doc, 'Annual inspection  (49 CFR 396.17)', y);
    doc.setFontSize(9.5);
    // The service record, or else the latest logged annual inspection.
    const logged = entries.find((e) => e.scheduleId === 'dot-annual');
    const lastRec = annual.last?.source === 'done' ? annual.last : logged;
    const last = lastRec
      ? `Last annual inspection: ${niceDate(lastRec.date)}${lastRec.note ? ` (${lastRec.note})` : ''}.`
      : 'Last annual inspection: not on record in aslog.dev.';
    const lines = doc.splitTextToSize(
      `${last} Next due: ${annual.dueDate ? niceDate(annual.dueDate) : '—'}. Keep the signed inspection report for 14 months; `
      + 'the report or a decal must be carried on the vehicle.',
      doc.internal.pageSize.getWidth() - 80,
    );
    doc.text(lines, 40, y + 6);
  }
}

/** Downloads a single truck's maintenance record. */
export async function downloadTruckRecord(opts) {
  const JsPDF = await loadPdfLib();
  const doc = new JsPDF({ unit: 'pt', format: 'letter' });
  addTruckRecord(doc, opts);
  footers(doc);
  doc.save(`maintenance-record-${fileSafe(opts.vehicle.name)}-${new Date().toLocaleDateString('en-CA')}.pdf`);
}

/** Downloads the service log as shown (date range, all units). */
export async function downloadLog({ entries, company, from, to }) {
  const JsPDF = await loadPdfLib();
  const doc = new JsPDF({ unit: 'pt', format: 'letter' });
  const period = from || to ? `${from ? niceDate(from) : 'start'} to ${to ? niceDate(to) : 'today'}` : 'All dates';
  const y = header(doc, 'Maintenance Log', company, `${period}  ·  ${entries.length} service${entries.length === 1 ? '' : 's'}`);
  doc.autoTable({
    ...tableStyle,
    startY: y + 4,
    head: [['Date', 'Unit', 'Work performed', 'Odometer', 'Engine h', 'Shop / notes']],
    body: entries.length
      ? entries.map((e) => [entryDate(e), e.vehicleName || e.vehicleId, workText(e), num(e.miles), num(e.hours), e.note || ''])
      : [[{ content: 'No services logged for this period.', colSpan: 6, styles: { textColor: 110 } }]],
    columnStyles: { 0: { cellWidth: 70 }, 1: { cellWidth: 48 }, 3: { cellWidth: 62, halign: 'right' }, 4: { cellWidth: 52, halign: 'right' } },
  });
  footers(doc);
  doc.save(`maintenance-log-${new Date().toLocaleDateString('en-CA')}.pdf`);
}
